services:
  baktobucket:
    build: 
      context: ./BakToBucket
      dockerfile: Dockerfile
    container_name: baktobucket
    restart: always
    env_file:
      - .env
    volumes:
      # Mount the folder where SQL Server saves .bak files (if SQL Server is used)
      - /path/to/host/sql_backups:/app/sql_backups
      # Mount the folder to store the final generated ZIP files
      - /path/to/host/archives:/app/Archives
